### ISSUE TITLE
Documented call to run quickstart.yaml has an error

### ISSUE THREAD

**Issue by rstens** [bcgov/nsp-to-knp-migration#10]
Roland_Stens
4:55 PM
Your update to network policy update causes

oc process -f quickstart.yaml  -p NAMESPACE=af2668-dev  oc apply -f -
error: template name must be specified only once: apply
See 'oc process -h' for help and examples

Run in git bash

Roland_Stens
5:02 PM
Were the network policies changed as well?

Roland_Stens
5:15 PM
Ah yes, forgot the pipe before oc apply

**Comment by mark-walle** [comment]
Needs a pipe to the second `oc` command, like:

`oc process -f quickstart.yaml -p NAMESPACE=af2668-dev | oc apply -f -`

**Comment by mark-walle** [comment]
https://github.com/bcgov/networkpolicy-migration-workshop/pull/11

**Comment by jleach** [comment]
Thx. Will apply to the new repo. Going to archive this one.
